export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS'
export const GET_COUNTRY_ERROR = 'GET_COUNTRY_ERROR'
export const CLEAR_COUNTRY_ERROR = 'CLEAR_COUNTRY_ERROR'

export const GET_COUNTRYLIST_SUCCESS = 'GET_COUNTRYLIST_SUCCESS'
export const GET_COUNTRYLIST_ERROR = 'GET_COUNTRYLIST_ERROR'
export const CLEAR_COUNTRYLIST_ERROR = 'CLEAR_COUNTRYLIST_ERROR'

export const GET_NEWSLIST_SUCCESS = 'GET_NEWSLIST_SUCCESS'
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS'
export const GET_NEWSLIST_ERROR = 'GET_NEWSLIST_ERROR'
export const CLEAR_ARTICLE_DATA = 'CLEAR_ARTICLE_DATA'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'